version: '3'
services:
  neo4j:
    image: neo4j:4.3.10
    container_name: neo4j
    restart: unless-stopped
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc"]
  arango:
    image: arangodb:3.8.4
    container_name: arango
    ports:
      - 8529:8529
    environment:
      - ARANGO_ROOT_PASSWORD=password
